[package]
name = "fictionary"
description = "A command-line tool that generates non-existent words."
authors = ["Mark Smith <judy@judy.co.uk>"]
version = "0.1.2"
edition = "2021"
license = "MIT"
homepage = "https://github.com/judy2k/fictionary-rs"
repository = "https://github.com/judy2k/fictionary-rs"
categories = ["command-line-utilities"]
exclude = [
  "HomebrewFormula",
  "/.github/",
  "/ci/",
]

[dependencies]
camino = "1.1.7"
clap = { version = "4.5.7", features = ["derive"] }
clap_complete = "4.5.6"
color-eyre = { version = "0.6", default-features = false }
counter = "0.5.7"
directories = "5.0.1"
eyre = "0.6.12"
postcard = { version = "1.0.8", features = ["use-std", "alloc"] }
serde = "1.0.203"
thiserror = "1.0.61"
weighted_rand = "0.4.2"
clap_mangen = "0.2.21"

# This is the main way to strip binaries in the deb package created by
# 'cargo deb'. For other release binaries, we (currently) call 'strip'
# explicitly in the release process.
[profile.deb]
inherits = "release"
debug = false

[package.metadata.deb]
section = "utils"
assets = [
  ["target/release/fictionary", "usr/bin/", "755"],
  ["LICENSE.txt", "usr/share/doc/fictionary/LICENSE", "644"],

  ["README.md", "usr/share/doc/ripgrep/README", "644"],
  # The man page is automatically generated by fictionary's build process, so
  # this file isn't actually committed. Instead, to create a dpkg,
  # create a deployment/deb directory and copy the man page to it.
  ["deployment/deb/fictionary.1", "usr/share/man/man1/fictionary.1", "644"],
  # Similarly for shell completions.
  ["deployment/deb/fictionary.bash", "usr/share/bash-completion/completions/fictionary", "644"],
  ["deployment/deb/fictionary.fish", "usr/share/fish/vendor_completions.d/fictionary.fish", "644"],
  ["deployment/deb/_fictionary", "usr/share/zsh/vendor-completions/", "644"],
  # Data files.
  ["deployment/deb/american.fictionary", "usr/share/fictionary/", "644"],
  ["deployment/deb/british.fictionary", "usr/share/fictionary/", "644"],
  ["deployment/deb/english.fictionary", "usr/share/fictionary/", "644"],
]
extended-description = """\
A command-line tool that generates non-existent words.
"""