#!/bin/bash

# This script builds a fictionary release for the aarch64-apple-darwin target.
# At time of writing (2024-06-25), GitHub Actions does not provide free Apple
# silicon runners. Since I have somewhat recently acquired an M2 mac mini,
# I just use this script to build the release tarball and upload it with `gh`.
#
# Once GitHub Actions has proper support for Apple silicon, we should add it
# to our release workflow and drop this script.

set -e

version="$1"
if [ -z "$version" ]; then
  echo "missing version" >&2
  echo "Usage: "$(basename "$0")" <version>" >&2
  exit 1
fi
if ! grep -q "version = \"$version\"" Cargo.toml; then
  echo "version does not match Cargo.toml" >&2
  exit 1
fi

target=aarch64-apple-darwin
cargo build --release --target $target
BIN=target/$target/release/fictionary
NAME=fictionary-$version-$target
ARCHIVE="deployment/m2/$NAME"

mkdir -p "$ARCHIVE"/{complete,doc,data}
cp "$BIN" "$ARCHIVE"/
strip "$ARCHIVE/fictionary"
# COPYING,UNLICENSE,LICENSE-MIT
cp {README.md,LICENSE.txt} "$ARCHIVE"/
# cp {CHANGELOG.md,FAQ.md,GUIDE.md} "$ARCHIVE"/doc/
"$BIN" completion bash > "$ARCHIVE/complete/fictionary.bash"
"$BIN" completion fish > "$ARCHIVE/complete/fictionary.fish"
"$BIN" completion powershell > "$ARCHIVE/complete/_fictionary.ps1"
"$BIN" completion zsh > "$ARCHIVE/complete/_fictionary"
"$BIN" completion man > "$ARCHIVE/doc/fictionary.1"
"$BIN" compile data/american.words "$ARCHIVE/data/american.fictionary"
"$BIN" compile data/british.words "$ARCHIVE/data/british.fictionary"
"$BIN" compile data/english.words "$ARCHIVE/data/english.fictionary"

tar c -C deployment/m2 -z -f "$ARCHIVE.tar.gz" "$NAME"
shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"
gh release upload "$version" "$ARCHIVE.tar.gz" "$ARCHIVE.tar.gz.sha256"
